/**
 * TRINETRA — Centralized Mock Data
 * ─────────────────────────────────
 * This is the single source of truth for all frontend data.
 * Replace these values / functions with real API calls
 * without touching any component code.
 */

// ── System State ─────────────────────────────────────────
const TrinetraState = {
  status: 'protected',   // protected | reviewing | threat_detected | recovering
  riskScore: 12,
  protectedFiles: 1204,
  recoveryVersions: 128,
  activeAgents: 6,
  lastScanTime: '2 minutes ago',
  realtimeProtection: true,
  canaryProtection: true,
};

// ── Agent Definitions ─────────────────────────────────────
const Agents = [
  {
    id: 'gatekeeper',
    name: 'Gatekeeper',
    icon: '🛡',
    description: 'First line of defense. Monitors all process creation and file access attempts, blocking known malicious patterns before they execute.',
    status: 'active',   // active | idle | alert | processing
    activity: 'Monitoring 847 active processes',
    checks: 14203,
    blocked: 0,
    lastAction: '2 min ago',
    detail: 'Real-time process monitor and access controller',
  },
  {
    id: 'watchdog',
    name: 'Watchdog',
    icon: '👁',
    description: 'Behavioral anomaly detector. Tracks file modification patterns, entropy changes, and write velocity to identify ransomware activity in real time.',
    status: 'active',
    activity: 'Watching 1,204 protected files',
    checks: 89421,
    blocked: 0,
    lastAction: '30 sec ago',
    detail: 'File behavior and entropy analyzer',
  },
  {
    id: 'risk-analyzer',
    name: 'Risk Analyzer',
    icon: '📊',
    description: 'Continuous threat scoring engine. Combines signals from all agents to compute a real-time risk score and determine threat classification.',
    status: 'active',
    activity: 'Risk score: 12 (Safe)',
    checks: 3847,
    blocked: 0,
    lastAction: '1 min ago',
    detail: 'Multi-signal threat scoring and classification',
  },
  {
    id: 'policy-engine',
    name: 'Policy Engine',
    icon: '⚖',
    description: 'Decision arbiter. Evaluates threat classifications against security policies and determines the appropriate automated response action.',
    status: 'active',
    activity: 'All policies nominal',
    checks: 1203,
    blocked: 0,
    lastAction: '3 min ago',
    detail: 'Policy evaluation and response orchestrator',
  },
  {
    id: 'enforcer',
    name: 'Enforcer',
    icon: '⚡',
    description: 'Rapid containment agent. Executes policy decisions by isolating processes, blocking network access, and preventing further file damage.',
    status: 'idle',
    activity: 'Standing by — no active threats',
    checks: 247,
    blocked: 0,
    lastAction: '47 min ago',
    detail: 'Process isolation and containment executor',
  },
  {
    id: 'vaultkeeper',
    name: 'Vaultkeeper',
    icon: '🔒',
    description: 'Recovery orchestrator. Maintains cryptographically verified file snapshots and orchestrates restoration from trusted backup points.',
    status: 'active',
    activity: 'Snapshot: 128 versions across 1,204 files',
    checks: 128,
    blocked: 0,
    lastAction: '5 min ago',
    detail: 'Encrypted snapshot and recovery manager',
  },
];

// ── File Versions ─────────────────────────────────────────
const Files = [
  {
    id: 'file_budget',
    name: 'budget.xlsx',
    icon: '📊',
    size: '2.4 MB',
    selected: true,
    versions: [
      {
        version: 7,
        label: 'V7',
        timestamp: 'Today, 10:42',
        trust: 'suspicious',
        writtenBy: 'unknown_process.exe',
        note: 'Content pattern changed abnormally',
        entropy: 'High entropy detected',
      },
      {
        version: 6,
        label: 'V6',
        timestamp: 'Today, 10:35',
        trust: 'trusted',
        writtenBy: 'EXCEL.EXE',
        note: 'Saved normally from Excel',
        entropy: 'Normal entropy',
        recommended: true,
      },
      {
        version: 5,
        label: 'V5',
        timestamp: 'Today, 09:48',
        trust: 'trusted',
        writtenBy: 'EXCEL.EXE',
        note: 'Saved normally from Excel',
        entropy: 'Normal entropy',
      },
    ],
  },
  {
    id: 'file_thesis',
    name: 'thesis_final.docx',
    icon: '📄',
    size: '8.1 MB',
    selected: false,
    versions: [
      {
        version: 4,
        label: 'V4',
        timestamp: 'Today, 10:44',
        trust: 'suspicious',
        writtenBy: 'unknown_process.exe',
        note: 'Mass binary modification',
        entropy: 'High entropy detected',
      },
      {
        version: 3,
        label: 'V3',
        timestamp: 'Today, 09:12',
        trust: 'trusted',
        writtenBy: 'WINWORD.EXE',
        note: 'Auto-saved from Word',
        entropy: 'Normal entropy',
        recommended: true,
      },
    ],
  },
  {
    id: 'file_contracts',
    name: 'client_contracts.pdf',
    icon: '📋',
    size: '5.7 MB',
    selected: false,
    versions: [
      {
        version: 2,
        label: 'V2',
        timestamp: 'Yesterday, 16:30',
        trust: 'trusted',
        writtenBy: 'Acrobat.exe',
        note: 'Saved from Adobe Acrobat',
        entropy: 'Normal entropy',
        recommended: true,
      },
    ],
  },
  {
    id: 'file_photos',
    name: 'family_photos.zip',
    icon: '🖼',
    size: '1.2 GB',
    selected: false,
    versions: [
      {
        version: 3,
        label: 'V3',
        timestamp: 'Yesterday, 22:10',
        trust: 'trusted',
        writtenBy: 'explorer.exe',
        note: 'User created archive',
        entropy: 'Normal entropy (compressed)',
        recommended: true,
      },
    ],
  },
];

// ── Recovery Status ───────────────────────────────────────
const RecoveryStatus = {
  totalFiles: 23,
  trustedCount: 23,
  recoveryPoints: 128,
  noFilesLost: true,
};

// ── Incident Data ─────────────────────────────────────────
const CurrentIncident = {
  id: null,
  active: false,
  severity: 'critical',
  riskScore: 96,
  title: 'Ransomware-like activity detected',
  summary: 'An unknown process attempted to encrypt your files. TRINETRA stopped it.',
  detectedAt: null,
  resolvedAt: null,
  detectionReasons: [
    'Mass file modifications in under 60 seconds',
    'High entropy content written (encryption signature)',
    'Unknown process with no digital signature',
    'File extension patterns match known ransomware families',
    'Canary file triggered by unknown_process.exe',
  ],
  detectionSignals: [
    { label: 'Write velocity', value: '47 files/sec', anomaly: true },
    { label: 'File entropy', value: '7.92 / 8.0', anomaly: true },
    { label: 'Process trust', value: 'Unknown / Unsigned', anomaly: true },
    { label: 'Canary triggered', value: 'Yes', anomaly: true },
    { label: 'Network calls', value: 'C2 server attempt', anomaly: true },
  ],
  actionsTaken: [
    { label: 'Process isolated', done: true },
    { label: 'Files protected', done: true },
    { label: 'Recovery point saved', done: true },
    { label: 'Network blocked', done: true },
    { label: 'Admin notified', done: true },
  ],
  affectedFiles: ['budget.xlsx', 'thesis_final.docx', 'client_contracts.pdf', 'family_photos.zip'],
};

// ── Security Event Log ────────────────────────────────────
const EventLog = [
  { time: '10:52', type: 'safe', icon: '✓', text: 'No threats detected today' },
  { time: '09:15', type: 'info', icon: 'ℹ', text: 'Run manual scan' },
  { time: '08:30', type: 'info', icon: '+', text: 'Add protected folder' },
  { time: '08:00', type: 'info', icon: '◔', text: 'View activity history' },
];

// ── History ───────────────────────────────────────────────
const IncidentHistory = [
  {
    id: 'inc_001',
    date: '2025-08-15',
    time: '14:23',
    title: 'Suspicious script execution blocked',
    severity: 'medium',
    riskScore: 54,
    status: 'resolved',
    duration: '3 min',
    filesAffected: 0,
  },
  {
    id: 'inc_002',
    date: '2025-08-10',
    time: '09:41',
    title: 'Canary file triggered — false positive',
    severity: 'low',
    riskScore: 28,
    status: 'resolved',
    duration: '45 sec',
    filesAffected: 0,
  },
  {
    id: 'inc_003',
    date: '2025-07-28',
    time: '23:17',
    title: 'Ransomware attempt — fully contained',
    severity: 'critical',
    riskScore: 98,
    status: 'resolved',
    duration: '22 sec',
    filesAffected: 0,
  },
];

// ── Simulation Timeline Events ────────────────────────────
const SimulationEvents = [
  {
    id: 'sim_0',
    time: '10:40:00',
    step: 0,
    title: 'Attack initiated',
    description: 'unknown_process.exe spawned by malicious email attachment',
    agent: null,
    agentName: '—',
    riskScore: 8,
    filesAffected: [],
    action: 'Process created, initial monitoring begins',
    type: 'attack',
    icon: '💀',
  },
  {
    id: 'sim_1',
    time: '10:40:02',
    step: 1,
    title: 'File modifications begin',
    description: 'Ransomware starts encrypting files at high velocity',
    agent: 'watchdog',
    agentName: 'Watchdog',
    riskScore: 22,
    filesAffected: ['budget.xlsx'],
    action: 'Watchdog detects anomalous write patterns',
    type: 'threat',
    icon: '📁',
  },
  {
    id: 'sim_2',
    time: '10:40:05',
    step: 2,
    title: 'Ransomware detected',
    description: 'Watchdog raises alert: 47 files/sec write velocity, entropy 7.92',
    agent: 'watchdog',
    agentName: 'Watchdog',
    riskScore: 47,
    filesAffected: ['budget.xlsx', 'thesis_final.docx'],
    action: 'Alert escalated to Risk Analyzer',
    type: 'detection',
    icon: '👁',
  },
  {
    id: 'sim_3',
    time: '10:40:08',
    step: 3,
    title: 'Risk score escalating',
    description: 'Risk Analyzer computes threat score from all signals',
    agent: 'risk-analyzer',
    agentName: 'Risk Analyzer',
    riskScore: 74,
    filesAffected: ['budget.xlsx', 'thesis_final.docx', 'client_contracts.pdf'],
    action: 'Score: 74 — CRITICAL threshold approaching',
    type: 'analysis',
    icon: '📊',
  },
  {
    id: 'sim_4',
    time: '10:40:11',
    step: 4,
    title: 'Policy decision: CONTAIN',
    description: 'Policy Engine classifies threat as RANSOMWARE_ATTACK, issues containment order',
    agent: 'policy-engine',
    agentName: 'Policy Engine',
    riskScore: 96,
    filesAffected: ['budget.xlsx', 'thesis_final.docx', 'client_contracts.pdf', 'family_photos.zip'],
    action: 'CONTAIN + ISOLATE + RECOVER policy triggered',
    type: 'decision',
    icon: '⚖',
  },
  {
    id: 'sim_5',
    time: '10:40:14',
    step: 5,
    title: 'Enforcer contains threat',
    description: 'Enforcer kills process, blocks network, freezes file writes',
    agent: 'enforcer',
    agentName: 'Enforcer',
    riskScore: 96,
    filesAffected: [],
    action: 'unknown_process.exe terminated. C2 network blocked.',
    type: 'containment',
    icon: '⚡',
  },
  {
    id: 'sim_6',
    time: '10:40:17',
    step: 6,
    title: 'Vaultkeeper restoring files',
    description: 'Vaultkeeper rolls back 23 files to last trusted snapshot',
    agent: 'vaultkeeper',
    agentName: 'Vaultkeeper',
    riskScore: 42,
    filesAffected: ['budget.xlsx', 'thesis_final.docx', 'client_contracts.pdf', 'family_photos.zip'],
    action: 'Restoring from V6 (trusted) snapshots',
    type: 'recovery',
    icon: '🔒',
  },
  {
    id: 'sim_7',
    time: '10:40:20',
    step: 7,
    title: 'System restored — threat neutralized',
    description: 'All 23 files restored. System fully protected. Risk score back to safe range.',
    agent: 'vaultkeeper',
    agentName: 'Vaultkeeper',
    riskScore: 12,
    filesAffected: [],
    action: 'Recovery complete. Incident report generated.',
    type: 'resolved',
    icon: '✅',
  },
];

// ── Settings Defaults ─────────────────────────────────────
const DefaultSettings = {
  threatNotifications: true,
  automaticResponse: true,
  backupFrequency: 'realtime',
  versionsToKeep: 10,
  trustedBackupPath: 'C:\\TRINETRA\\vault',
  emailAlerts: true,
  smsAlerts: false,
};

// ── Export all ────────────────────────────────────────────
window.TrinetraMockData = {
  state: TrinetraState,
  agents: Agents,
  files: Files,
  recoveryStatus: RecoveryStatus,
  currentIncident: CurrentIncident,
  eventLog: EventLog,
  history: IncidentHistory,
  simulation: SimulationEvents,
  settings: DefaultSettings,
};
